baseURL = 'https://poliview.github.io/'
languageCode = 'en-us'
title = '政文观止Poliview'
theme = "PaperMod"
enableEmoji = true
publishDir = "docs"
hasCJKLanguage = true
relativeURLs = true
canonifyURLs= false